
//////////////////////////
//BATCH ATTACK CONSTANTS//
//////////////////////////
export const TICK = 20;
export const SNIPPET_RAM_COST = 1.75;
// export const SNIPPET_RAM_COST = 2.05;
export const SNIPPET_PREFIX_WAIT = 'wait';
export const SNIPPET_FILENAME_GROW = 'grow.js';

export const SNIPPET_FILENAME_HACK = 'hack.js';
export const SNIPPET_FILENAME_WEAKEN = 'weaken.js';
export const SNIPPET_FILENAME_SHARE = 'share.js';

export const SNIPPETS_PATH = '/utils/snippets/';
export const SNIPPET_PATH_GROW = SNIPPETS_PATH + SNIPPET_FILENAME_GROW;
export const SNIPPET_PATH_HACK = SNIPPETS_PATH + SNIPPET_FILENAME_HACK;
export const SNIPPET_PATH_WEAKEN = SNIPPETS_PATH + SNIPPET_FILENAME_WEAKEN;
export const SNIPPET_PATH_SHARE = SNIPPETS_PATH + SNIPPET_FILENAME_SHARE;

export const SNIPPET_PATH_WAIT_GROW = SNIPPETS_PATH + SNIPPET_PREFIX_WAIT + SNIPPET_FILENAME_GROW;
export const SNIPPET_PATH_WAIT_HACK = SNIPPETS_PATH + SNIPPET_PREFIX_WAIT + SNIPPET_FILENAME_HACK;
export const SNIPPET_PATH_WAIT_WEAKEN = SNIPPETS_PATH + SNIPPET_PREFIX_WAIT + SNIPPET_FILENAME_WEAKEN;

export const SNIPPETS = [
    {
        'file': SNIPPET_FILENAME_GROW,
        'path': SNIPPET_PATH_GROW,
    },
    {
        'file': SNIPPET_FILENAME_HACK,
        'path': SNIPPET_PATH_HACK,
    },
    {
        'file': SNIPPET_FILENAME_WEAKEN,
        'path': SNIPPET_PATH_WEAKEN,
    },
    {
        'file': SNIPPET_FILENAME_SHARE,
        'path': SNIPPET_PATH_SHARE,
    },
    {
        'file': SNIPPET_PREFIX_WAIT + SNIPPET_FILENAME_GROW,
        'path': SNIPPET_PATH_WAIT_GROW,
    },
    {
        'file': SNIPPET_PREFIX_WAIT + SNIPPET_FILENAME_HACK,
        'path': SNIPPET_PATH_WAIT_HACK,
    },
    {
        'file': SNIPPET_PREFIX_WAIT + SNIPPET_FILENAME_WEAKEN,
        'path': SNIPPET_PATH_WAIT_WEAKEN,
    },
];

export const ATTACK_TYPE_PREPARE_WEAKEN = 0;
export const ATTACK_TYPE_PREPARE_GROW = 1;
export const ATTACK_TYPE_HACK = 2;
export const ATTACK_TYPE_WEAKEN = 3;
export const ATTACK_TYPE_GROW = 4;

export const ATTACK_TYPES = {
    [SNIPPET_PATH_WEAKEN]: ATTACK_TYPE_PREPARE_WEAKEN,
    [SNIPPET_PATH_GROW]: ATTACK_TYPE_PREPARE_GROW,
    [SNIPPET_PATH_WAIT_HACK]: ATTACK_TYPE_HACK,
    [SNIPPET_PATH_WAIT_WEAKEN]: ATTACK_TYPE_WEAKEN,
    [SNIPPET_PATH_WAIT_GROW]: ATTACK_TYPE_GROW,
};


export const GROW_THREAD_SECURITY_INCREASE = 0.004;
export const HACK_THREAD_SECURITY_INCREASE = 0.002;
export const WEAKEN_THREAD_SECURITY_DECREASE = 0.05;

export const BATCH_ATTACK_TYPE_HACK = 0;
export const BATCH_ATTACK_TYPE_HACK_WEAKEN = 1;
export const BATCH_ATTACK_TYPE_GROW = 2;
export const BATCH_ATTACK_TYPE_GROW_WEAKEN = 3;