import {
    SERVER_NAME_AVMNITE_02H,
    SERVER_NAME_CSEC,
    SERVER_NAME_I_I_I_I,
    SERVER_NAME_RUN4THEH111Z
} from "/constants/ServerNames";

//////////////////////////
//FACTION NAME CONSTANTS//
//////////////////////////

export const FACTION_NAME_CYBERSEC = 'CyberSec';
export const FACTION_NAME_TIAN_DI_HUI = 'Tian Di Hui';
export const FACTION_NAME_NETBURNERS = 'Netburners';
export const FACTION_NAME_SHADOWS_OF_ANARCHY = 'Shadows of Anarchy';
export const FACTION_NAME_SECTOR_12 = 'Sector-12';
export const FACTION_NAME_CHONGQING = 'Chongqing';
export const FACTION_NAME_NEW_TOKYO = 'New Tokyo';
export const FACTION_NAME_ISHIMA = 'Ishima';
export const FACTION_NAME_AEVUM = 'Aevum';
export const FACTION_NAME_VOLHAVEN = 'Volhaven';
export const FACTION_NAME_NITESEC = 'NiteSec';
export const FACTION_NAME_THE_BLACK_HAND = 'The Black Hand';
export const FACTION_NAME_BITRUNNERS = 'BitRunners';
export const FACTION_NAME_ECORP = 'ECorp';
export const FACTION_NAME_MEGACORP = 'MegaCorp';
export const FACTION_NAME_KUAIGONG_INTERNATIONAL = 'KuaiGong International';
export const FACTION_NAME_FOUR_SIGMA = 'Four Sigma';
export const FACTION_NAME_NWO = 'NWO';
export const FACTION_NAME_BLADE_INDUSTRIES = 'Blade Industries';
export const FACTION_NAME_OMNITEK_INCORPORATED = 'OmniTek Incorporated';
export const FACTION_NAME_BACHMAN_AND_ASSOCIATES = 'Bachman & Associates';
export const FACTION_NAME_CLARKE_INCORPORATED = 'Clarke Incorporated';
export const FACTION_NAME_FULCRUM_SECRET_TECHNOLOGIES = 'Fulcrum Secret Technologies';
export const FACTION_NAME_SLUM_SNAKES = 'Slum Snakes';
export const FACTION_NAME_TETRADS = 'Tetrads';
export const FACTION_NAME_SILHOUETTE = 'Silhouette';
export const FACTION_NAME_SPEAKERS_FOR_THE_DEAD = 'Speakers for the Dead';
export const FACTION_NAME_THE_DARK_ARMY = 'The Dark Army';
export const FACTION_NAME_THE_SYNDICATE = 'The Syndicate';
export const FACTION_NAME_THE_COVENANT = 'The Covenant';
export const FACTION_NAME_DAEDALUS = 'Daedalus';
export const FACTION_NAME_ILLUMINATI = 'Illuminati';

///////////////////////////
//FACTION GROUP CONSTANTS//
///////////////////////////
export const FACTIONS_EARLY_GAME = [
    FACTION_NAME_CYBERSEC,
    FACTION_NAME_TIAN_DI_HUI,
    FACTION_NAME_NETBURNERS,
    FACTION_NAME_SHADOWS_OF_ANARCHY,
];

export const FACTIONS_CITY = [
    FACTION_NAME_SECTOR_12,
    FACTION_NAME_CHONGQING,
    FACTION_NAME_NEW_TOKYO,
    FACTION_NAME_ISHIMA,
    FACTION_NAME_AEVUM,
    FACTION_NAME_VOLHAVEN,
];

export const FACTIONS_HACKING = [
    FACTION_NAME_NITESEC,
    FACTION_NAME_THE_BLACK_HAND,
    FACTION_NAME_BITRUNNERS,
];

export const FACTIONS_MEGACORPORATIONS = [
    FACTION_NAME_ECORP,
    FACTION_NAME_MEGACORP,
    FACTION_NAME_KUAIGONG_INTERNATIONAL,
    FACTION_NAME_FOUR_SIGMA,
    FACTION_NAME_NWO,
    FACTION_NAME_BLADE_INDUSTRIES,
    FACTION_NAME_OMNITEK_INCORPORATED,
    FACTION_NAME_BACHMAN_AND_ASSOCIATES,
    FACTION_NAME_CLARKE_INCORPORATED,
    FACTION_NAME_FULCRUM_SECRET_TECHNOLOGIES,
];

export const FACTIONS_CRIMINAL = [
    FACTION_NAME_SLUM_SNAKES,
    FACTION_NAME_TETRADS,
    FACTION_NAME_SILHOUETTE,
    FACTION_NAME_SPEAKERS_FOR_THE_DEAD,
    FACTION_NAME_THE_DARK_ARMY,
    FACTION_NAME_THE_SYNDICATE,
];

export const FACTIONS_ENDGAME = [
    FACTION_NAME_THE_COVENANT,
    FACTION_NAME_DAEDALUS,
    FACTION_NAME_ILLUMINATI,
];

export const FACTIONS_BACKDOOR_REQUIREMENTS = {
    [FACTION_NAME_CYBERSEC]: SERVER_NAME_CSEC,
    [FACTION_NAME_NITESEC]: SERVER_NAME_AVMNITE_02H,
    [FACTION_NAME_THE_BLACK_HAND]: SERVER_NAME_I_I_I_I,
    [FACTION_NAME_BITRUNNERS]: SERVER_NAME_RUN4THEH111Z,
}

export const FACTIONS_DONT_AUTO_JOIN = [
    FACTION_NAME_SECTOR_12,
    FACTION_NAME_CHONGQING,
    FACTION_NAME_NEW_TOKYO,
    FACTION_NAME_ISHIMA,
    FACTION_NAME_AEVUM,
    FACTION_NAME_VOLHAVEN,
];