import {
    SERVER_NAME_FULCRUMASSETS,
    SERVER_NAME_IRON_GYM,
    SERVER_NAME_POWERHOUSE_FITNESS,
    SERVER_NAME_THE_CAVE
} from "/constants/ServerNames";

export const FILENAME_GRACEFUL_KILL = 'kill.txt';

export const ADDITIONAL_BACKDOORS = [
    SERVER_NAME_FULCRUMASSETS,
    SERVER_NAME_IRON_GYM,
    SERVER_NAME_POWERHOUSE_FITNESS,
    SERVER_NAME_THE_CAVE,
    // SERVER_NAME_,
];